default:
ifndef DNANEXUS_HOME
	$(error DNANEXUS_HOME environment variable is not set; please source /path/to/dx-toolkit/environment)
endif
	$(MAKE) -C src

clean:
	$(MAKE) -C src clean

.PHONY: default
